import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router";
import { routePaths } from "../../../app/routes/paths";
import { Badge, Button, Input, Select, Textarea } from "../../../components/atoms";
import { Alert, LoadingState } from "../../../components/feedback";
import { FormField, FormGroup, SectionHeader, SearchableSelect } from "../../../components/molecules";
import { DataTable, type DataTableColumn } from "../../../components/organisms";
import { usePermissions } from "../../auth";
import { CatalogItemSelect } from "../../catalog/components/CatalogItemSelect";
import { currencyService } from "../../currency/currencyService";
import { customerService } from "../../customers/services/customerService";
import { lenderService } from "../../lenders/services/lenderService";
import type { Currency } from "../../currency/types";
import { purchasingService } from "../services/purchasingService";
import type { PurchaseOrder, PurchasePayment, PurchaseReceipt, PurchaseReturn, PurchaseSupplier, PurchaseTrackingMode, SupplierType } from "../types";
import "./purchasing.css";

type LineDraft = { catalog_item_code: string; item_description: string; tracking_mode: PurchaseTrackingMode; unit_label: string; ordered_quantity: string; unit_price: string; received_quantity: string };
const blankLine = (): LineDraft => ({ catalog_item_code: "", item_description: "", tracking_mode: "QUANTITY", unit_label: "Unit", ordered_quantity: "1", unit_price: "", received_quantity: "1" });
const today = () => new Date().toISOString().slice(0, 10);
const money = (value: string | number, currency: string) => `${Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })} ${currency}`;
const errorText = (e: unknown) => e instanceof Error ? e.message : "Something went wrong. Please try again.";

export function PurchasingPage() {
  const [orders, setOrders] = useState<PurchaseOrder[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const navigate = useNavigate(); const { hasPermission } = usePermissions();
  const load = useCallback(async () => { setLoading(true); try { setOrders(await purchasingService.orders(search)); setError(""); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } }, [search]);
  useEffect(() => { void load(); }, [load]);
  const columns: Array<DataTableColumn<PurchaseOrder>> = [
    { header: "Purchase code", key: "code", render: o => <strong>{o.code}</strong> },
    { header: "Supplier", key: "supplier", render: o => o.supplier.name },
    { header: "Date", key: "date", render: o => o.ordered_at ?? new Date(o.created_at).toLocaleDateString() },
    { header: "Total", key: "amount", align: "right", render: o => money(o.totals.amount, o.currency_code) },
    { header: "Order status", key: "status", render: o => <Badge>{o.status}</Badge> },
    { header: "Payment", key: "payment", render: o => <Badge>{o.payment_status}</Badge> },
    { header: "Receipt", key: "receipt", render: o => <Badge>{o.receipt_status}</Badge> },
  ];
  return <main className="page-content"><SectionHeader title="Purchasing" subtitle="Record purchases, check deliveries, and follow payments." action={<div className="purchasing-actions">{hasPermission("manage_purchase_order") && <><Link className="ui-button ui-button--primary" to={routePaths.purchasingCreate}>Record a purchase</Link><Link className="ui-button ui-button--secondary" to={`${routePaths.purchasingCreate}?mode=order`}>Create purchase order</Link></>}<Link className="ui-button ui-button--secondary" to={routePaths.purchasingSuppliers}>Suppliers</Link></div>} />
    {error && <Alert tone="danger" title="Unable to load purchases" message={error} />}
    <FormField id="purchase-search" label="Search purchases"><Input id="purchase-search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Purchase code or supplier" /></FormField>
    <DataTable columns={columns} items={orders} isLoading={loading} getItemId={o => o.code} getItemTitle={o => o.code} onRowClick={o => navigate(routePaths.purchasingOrder(o.code))} emptyTitle="No purchases yet" emptyDescription="Record your first purchase to see it here." />
  </main>;
}

export function PurchaseCreatePage() {
  const [searchParams] = useSearchParams();
  const [suppliers, setSuppliers] = useState<PurchaseSupplier[]>([]); const [currencies, setCurrencies] = useState<Currency[]>([]); const [supplierCode, setSupplierCode] = useState(""); const [addingSupplier, setAddingSupplier] = useState(false); const [newSupplierName, setNewSupplierName] = useState(""); const [newSupplierPhone, setNewSupplierPhone] = useState(""); const [newSupplierType, setNewSupplierType] = useState<SupplierType>("SHOP"); const [currencyCode, setCurrencyCode] = useState(""); const [note, setNote] = useState(""); const [lines, setLines] = useState<LineDraft[]>([blankLine()]); const [date, setDate] = useState(today()); const [quick, setQuick] = useState(searchParams.get("mode") !== "order"); const [payNow, setPayNow] = useState(false); const [payAmount, setPayAmount] = useState(""); const [payReference, setPayReference] = useState(""); const [payNote, setPayNote] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [created, setCreated] = useState<PurchaseOrder | null>(null); const [progress, setProgress] = useState(""); const navigate = useNavigate(); const { hasPermission } = usePermissions();
  useEffect(() => { void Promise.all([purchasingService.suppliers(), currencyService.listCurrencies()]).then(([s, c]) => { setSuppliers(s.filter(x => x.is_active)); setCurrencies(c.items.filter(x => x.is_active)); const defaultCurrency = c.items.find(x => x.is_default && x.is_active) ?? c.items.find(x => x.is_active); if (defaultCurrency) setCurrencyCode(defaultCurrency.code); }).catch(e => setError(errorText(e))); }, []);
  const total = useMemo(() => lines.reduce((sum, l) => sum + Number(l.ordered_quantity || 0) * Number(l.unit_price || 0), 0), [lines]);
  function updateLine(index: number, patch: Partial<LineDraft>) { setLines(current => current.map((line, i) => i === index ? { ...line, ...patch } : line)); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setLoading(true);
    let createdOrderCode = "";
    try {
      if ((!supplierCode && (!addingSupplier || !newSupplierName.trim())) || !currencyCode || lines.some(l => !l.unit_price || Number(l.ordered_quantity) <= 0 || (l.catalog_item_code === "" && !l.item_description.trim()))) throw new Error("Choose a supplier and complete each item row.");
      const selectedSupplierCode = supplierCode || (await purchasingService.createSupplier({ type: newSupplierType, name: newSupplierName.trim(), phone: newSupplierPhone || null })).code;
      if (!supplierCode) { setSupplierCode(selectedSupplierCode); setAddingSupplier(false); }
      const order = await purchasingService.createOrder({ supplier_code: selectedSupplierCode, currency_code: currencyCode, note: note || undefined, lines: lines.map(l => ({ catalog_item_code: l.catalog_item_code || null, item_description: l.catalog_item_code ? undefined : l.item_description.trim(), tracking_mode: l.tracking_mode, unit_label: l.unit_label, ordered_quantity: Number(l.ordered_quantity), unit_price: Number(l.unit_price) })) });
      createdOrderCode = order.code; setCreated(order);
      if (!quick) { navigate(routePaths.purchasingOrder(order.code)); return; }
      setProgress("Purchase saved. Placing the order...");
      await purchasingService.orderAction(order.code, "order"); setProgress("Order placed. Confirming with supplier...");
      await purchasingService.orderAction(order.code, "confirm");
      const receiveLines = order.lines?.map((line, i) => ({ purchase_order_line_code: line.code, quantity: Number(lines[i]?.received_quantity || 0) })).filter(l => l.quantity > 0) ?? [];
      if (quick && receiveLines.length) { setProgress("Supplier confirmed. Recording received goods..."); await purchasingService.receive(order.code, { received_at: date, lines: receiveLines }); }
      if (payNow && Number(payAmount) > 0) { setProgress("Recording payment..."); await purchasingService.recordPayment(order.code, { paid_at: date, amount: Number(payAmount), reference: payReference || undefined, note: payNote || undefined }); }
      navigate(routePaths.purchasingOrder(order.code));
    } catch (e) { setError(errorText(e)); const code = createdOrderCode || created?.code; if (code) { setCreated(current => current ?? ({ code } as PurchaseOrder)); setProgress("Purchase was created. Open its details to continue from the last completed step."); } }
    finally { setLoading(false); }
  }
  return <main className="page-content"><SectionHeader title="Record a purchase" subtitle="Enter goods bought from a supplier." />
    {error && <Alert tone="danger" title="Purchase not fully saved" message={error} action={created ? <>Purchase code: <Link to={routePaths.purchasingOrder(created.code)}>{created.code}</Link></> : undefined} />}
    {progress && <Alert tone="info" title="Purchase progress" message={progress} />}
    <form onSubmit={submit} className="purchasing-form"><FormGroup title="Purchase details">
      {!addingSupplier ? <><FormField id="purchase-supplier" label="Supplier"><SearchableSelect id="purchase-supplier" value={supplierCode} options={suppliers} getOptionValue={s => s.code} getOptionLabel={s => s.name} getOptionDescription={s => s.code} onChange={setSupplierCode} onSearchChange={q => { void purchasingService.suppliers(q).then(setSuppliers); }} placeholder="Search suppliers" emptyMessage="No suppliers found." /></FormField>{hasPermission("manage_supplier")&&<Button type="button" variant="tertiary" onClick={()=>{setAddingSupplier(true);setSupplierCode("")}}>Add supplier</Button>}</> : <div className="purchase-inline-supplier"><FormField id="new-supplier-name" label="New supplier name"><Input id="new-supplier-name" required value={newSupplierName} onChange={e=>setNewSupplierName(e.target.value)} /></FormField><FormField id="new-supplier-type" label="Supplier type"><Select id="new-supplier-type" value={newSupplierType} onChange={e=>setNewSupplierType(e.target.value as SupplierType)}><option value="SHOP">Shop</option><option value="SUPPLIER">Supplier</option><option value="ONLINE_STORE">Online store</option><option value="INDIVIDUAL">Individual</option></Select></FormField><FormField id="new-supplier-phone" label="Phone"><Input id="new-supplier-phone" value={newSupplierPhone} onChange={e=>setNewSupplierPhone(e.target.value)} /></FormField><Button type="button" onClick={()=>setAddingSupplier(false)}>Choose existing supplier</Button></div>}
      <FormField id="purchase-currency" label="Currency"><Select id="purchase-currency" value={currencyCode} onChange={e => setCurrencyCode(e.target.value)}><option value="">Choose currency</option>{currencies.map(c => <option key={c.code} value={c.code}>{c.code} — {c.name}</option>)}</Select></FormField>
      <FormField id="purchase-date" label={quick ? "Purchase date" : "Order date"}><Input id="purchase-date" type="date" value={date} onChange={e => setDate(e.target.value)} /></FormField>
      <FormField id="purchase-note" label="Note"><Textarea id="purchase-note" value={note} onChange={e => setNote(e.target.value)} rows={2} /></FormField>
    </FormGroup>
    <FormGroup title="Goods">
      {lines.map((line, index) => <div className="purchase-line" key={index}>
        <CatalogItemSelect id={`catalog-${index}`} value={line.catalog_item_code} onChange={(_, item) => updateLine(index, item ? { catalog_item_code: item.business_code, item_description: item.name, tracking_mode: item.tracking_mode, unit_label: item.unit?.name ?? "Unit", ...(item.tracking_mode === "UNIQUE" ? { ordered_quantity: "1", received_quantity: quick ? "1" : line.received_quantity } : {}) } : { catalog_item_code: "" })} />
        {!line.catalog_item_code && <FormField id={`description-${index}`} label="Item description"><Input id={`description-${index}`} value={line.item_description} onChange={e => updateLine(index, { item_description: e.target.value })} placeholder="Describe this item" /></FormField>}
        <FormField id={`tracking-${index}`} label="Tracking"><Select id={`tracking-${index}`} value={line.tracking_mode} onChange={e => { const trackingMode=e.target.value as PurchaseTrackingMode; updateLine(index, { tracking_mode: trackingMode, ...(trackingMode === "UNIQUE" ? { ordered_quantity: "1", received_quantity: quick ? "1" : line.received_quantity } : {}) }); }}><option value="QUANTITY">Quantity</option><option value="SERIALIZED">Serialized</option><option value="UNIQUE">Unique item</option></Select></FormField>
        <FormField id={`unit-${index}`} label="Unit"><Input id={`unit-${index}`} value={line.unit_label} onChange={e => updateLine(index, { unit_label: e.target.value })} /></FormField>
        <FormField id={`qty-${index}`} label="Quantity"><Input id={`qty-${index}`} type="number" min={line.tracking_mode === "UNIQUE" ? "1" : "0.001"} step={line.tracking_mode === "QUANTITY" ? "0.001" : "1"} disabled={line.tracking_mode === "UNIQUE"} value={line.ordered_quantity} onChange={e => updateLine(index, { ordered_quantity: e.target.value, received_quantity: quick ? e.target.value : line.received_quantity })} /></FormField>
        {quick && <FormField id={`received-${index}`} label="Received now"><Input id={`received-${index}`} type="number" min="0" step={line.tracking_mode === "QUANTITY" ? "0.001" : "1"} max={line.ordered_quantity} disabled={line.tracking_mode === "UNIQUE"} value={line.received_quantity} onChange={e => updateLine(index, { received_quantity: e.target.value })} /></FormField>}
        <FormField id={`price-${index}`} label="Unit price"><Input id={`price-${index}`} type="number" min="0" step="0.01" value={line.unit_price} onChange={e => updateLine(index, { unit_price: e.target.value })} /></FormField>
        <Button type="button" variant="tertiary" onClick={() => setLines(current => current.length > 1 ? current.filter((_, i) => i !== index) : current)}>Remove</Button>
      </div>)}
      <Button type="button" onClick={() => setLines(current => [...current, blankLine()])}>Add item</Button>
      <p className="purchase-total"><strong>Total: {money(total, currencyCode || "")}</strong></p>
    </FormGroup>
    <FormGroup title="Receipt and payment">
      <label className="purchase-check"><input type="checkbox" checked={quick} onChange={e => setQuick(e.target.checked)} /> Goods are already received (quick purchase)</label>
      {quick && <p>Received quantities will be recorded. Stock and ownership balances are not updated yet.</p>}
      {quick ? <><label className="purchase-check"><input type="checkbox" checked={payNow} onChange={e => setPayNow(e.target.checked)} /> Record a payment now</label>{payNow && <><FormField id="paid-amount" label="Paid amount"><Input id="paid-amount" type="number" min="0.01" step="0.01" max={total} value={payAmount} onChange={e => setPayAmount(e.target.value)} /></FormField><FormField id="payment-reference" label="Payment reference"><Input id="payment-reference" value={payReference} onChange={e=>setPayReference(e.target.value)} /></FormField><FormField id="payment-note" label="Payment note"><Textarea id="payment-note" value={payNote} onChange={e=>setPayNote(e.target.value)} /></FormField></>}</> : <p>Save this as a draft. You can place the order and record payment or deliveries later.</p>}
    </FormGroup>
    <div className="purchasing-actions"><Button type="button" onClick={() => navigate(routePaths.purchasing)}>Cancel</Button><Button type="submit" variant="primary" isLoading={loading} disabled={loading || (!suppliers.length && !addingSupplier) || !currencies.length}>Save purchase</Button></div>
    </form>
  </main>;
}

export function PurchaseSuppliersPage() {
  const [items, setItems] = useState<PurchaseSupplier[]>([]); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [editing, setEditing] = useState<PurchaseSupplier | null>(null); const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [type, setType] = useState<SupplierType>("SHOP"); const [contactName, setContactName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [address, setAddress] = useState(""); const [note, setNote] = useState(""); const [active, setActive] = useState(true); const [partyKind, setPartyKind] = useState<"new" | "customer" | "lender">("new"); const [partyCode, setPartyCode] = useState(""); const [customers, setCustomers] = useState<Array<{code:string;name:string}>>([]); const [lenders, setLenders] = useState<Array<{code:string;name:string}>>([]); const { hasPermission } = usePermissions();
  const load = useCallback(async () => { setLoading(true); try { setItems(await purchasingService.suppliers(search)); setError(""); } catch(e) { setError(errorText(e)); } finally { setLoading(false); } }, [search]); useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (partyKind === "customer") void customerService.listCustomers({ page: 1, perPage: 100 }).then(p => setCustomers(p.items.map(x => ({code:x.code,name:x.name})))).catch(() => setError("Unable to load customers.")); if (partyKind === "lender") void lenderService.list({ page: 1, perPage: 100 }).then(p => setLenders(p.data.map(x => ({code:x.code,name:x.name})))).catch(() => setError("Unable to load lenders.")); }, [partyKind]);
  async function save(e: FormEvent) { e.preventDefault(); setError(""); try { if (editing) await purchasingService.updateSupplier(editing.code, { type, contact_name: contactName || null, note: note || null, is_active: active }); else await purchasingService.createSupplier({ type, ...(partyKind === "customer" ? { customer_code: partyCode } : partyKind === "lender" ? { lender_code: partyCode } : { name }), contact_name: contactName || null, phone: partyKind === "new" ? phone || null : undefined, email: partyKind === "new" ? email || null : undefined, address: partyKind === "new" ? address || null : undefined, note: note || null }); setCreating(false); setEditing(null); setName(""); setPartyCode(""); await load(); } catch(e) { setError(errorText(e)); } }
  const columns: Array<DataTableColumn<PurchaseSupplier>> = [{header:"Supplier",key:"name",render:s=><strong>{s.name}</strong>},{header:"Type",key:"type",render:s=>s.type.replaceAll("_"," ")},{header:"Phone",key:"phone",render:s=>s.phone||"—"},{header:"Linked record",key:"linked",render:s=>s.customer_code?`Customer ${s.customer_code}`:s.lender_code?`Lender ${s.lender_code}`:"—"},{header:"Status",key:"active",render:s=><Badge>{s.is_active?"Active":"Inactive"}</Badge>}];
  return <main className="page-content"><SectionHeader title="Suppliers" subtitle="Suppliers share contact details with Customers and Lenders when linked." action={<Link className="ui-button ui-button--secondary" to={routePaths.purchasing}>Purchases</Link>} />
    {error&&<Alert tone="danger" title="Supplier action failed" message={error} />}<div className="purchasing-actions"><Input aria-label="Search suppliers" placeholder="Search suppliers" value={search} onChange={e=>setSearch(e.target.value)} />{hasPermission("manage_supplier")&&<Button variant="primary" onClick={()=>{setCreating(true);setEditing(null)}}>Add supplier</Button>}</div>
    <DataTable columns={columns} items={items} isLoading={loading} getItemId={s=>s.code} getItemTitle={s=>s.name} actions={s=>hasPermission("manage_supplier")?<Button onClick={()=>{setEditing(s);setCreating(true);setName(s.name);setType(s.type);setContactName(s.contact_name??"");setPhone(s.phone??"");setEmail(s.email??"");setAddress(s.address??"");setNote(s.note??"");setActive(s.is_active)}}>Edit</Button>:null} emptyTitle="No suppliers yet" emptyDescription="Add a supplier to use on purchase records." />
    {creating&&<div className="purchase-modal" role="dialog" aria-modal="true"><form onSubmit={save} className="purchase-modal__panel"><SectionHeader title={editing?"Edit supplier":"Add supplier"} />
      {!editing&&<FormField id="party-kind" label="Supplier contact"><Select id="party-kind" value={partyKind} onChange={e=>{setPartyKind(e.target.value as typeof partyKind);setPartyCode("")}}><option value="new">New contact</option><option value="customer">Existing Customer</option><option value="lender">Existing Lender</option></Select></FormField>}
      {partyKind==="new"&&!editing&&<FormField id="supplier-name" label="Name"><Input id="supplier-name" required value={name} onChange={e=>setName(e.target.value)} /></FormField>}
      {(partyKind==="customer"||partyKind==="lender")&&!editing&&<FormField id="party-code" label={partyKind==="customer"?"Customer":"Lender"}><Select id="party-code" required value={partyCode} onChange={e=>setPartyCode(e.target.value)}><option value="">Choose {partyKind}</option>{(partyKind==="customer"?customers:lenders).map(p=><option key={p.code} value={p.code}>{p.name} ({p.code})</option>)}</Select></FormField>}
      <FormField id="supplier-type" label="Supplier type"><Select id="supplier-type" value={type} onChange={e=>setType(e.target.value as SupplierType)}><option value="INDIVIDUAL">Individual</option><option value="SUPPLIER">Supplier</option><option value="SHOP">Shop</option><option value="ONLINE_STORE">Online store</option></Select></FormField>
      {partyKind==="new"&&!editing&&<><FormField id="supplier-phone" label="Phone"><Input id="supplier-phone" value={phone} onChange={e=>setPhone(e.target.value)} /></FormField><FormField id="supplier-email" label="Email"><Input id="supplier-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} /></FormField><FormField id="supplier-address" label="Address"><Textarea id="supplier-address" value={address} onChange={e=>setAddress(e.target.value)} /></FormField></>}
      {editing&&<FormField id="supplier-active" label="Status"><Select id="supplier-active" value={active?"1":"0"} onChange={e=>setActive(e.target.value==="1")}><option value="1">Active</option><option value="0">Inactive</option></Select></FormField>}
      <FormField id="supplier-contact" label="Contact name"><Input id="supplier-contact" value={contactName} onChange={e=>setContactName(e.target.value)} /></FormField><FormField id="supplier-note" label="Note"><Textarea id="supplier-note" value={note} onChange={e=>setNote(e.target.value)} /></FormField>
      <div className="purchasing-actions"><Button type="button" onClick={()=>setCreating(false)}>Cancel</Button><Button type="submit" variant="primary">Save supplier</Button></div></form></div>}
  </main>;
}

export function PurchaseOrderDetailPage() {
  const { orderCode = "" } = useParams(); const [order,setOrder]=useState<PurchaseOrder|null>(null); const [payments,setPayments]=useState<PurchasePayment[]>([]); const [receipts,setReceipts]=useState<PurchaseReceipt[]>([]); const [returns,setReturns]=useState<PurchaseReturn[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [mode,setMode]=useState<"payment"|"receive"|"return"|"refund"|null>(null); const [amount,setAmount]=useState(""); const [date,setDate]=useState(today()); const [note,setNote]=useState(""); const [reference,setReference]=useState(""); const [returnReason,setReturnReason]=useState(""); const [lineQty,setLineQty]=useState<Record<string,string>>({}); const [paymentCode,setPaymentCode]=useState(""); const {hasPermission}=usePermissions();
  const load=useCallback(async()=>{setLoading(true);try{const [o,p,r,ret]=await Promise.all([purchasingService.order(orderCode),purchasingService.payments(orderCode),purchasingService.receipts(orderCode),purchasingService.returns(orderCode)]);setOrder(o);setPayments(p);setReceipts(r);setReturns(ret);setError("");}catch(e){setError(errorText(e));}finally{setLoading(false);}},[orderCode]);useEffect(()=>{void load()},[load]);
  async function action(action:"order"|"confirm"|"cancel"){setBusy(true);try{await purchasingService.orderAction(orderCode,action);await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  async function submitAction(e:FormEvent){e.preventDefault();if(!order)return;setBusy(true);setError("");try{if(mode==="payment")await purchasingService.recordPayment(order.code,{paid_at:date,amount:Number(amount),reference:reference||undefined,note:note||undefined});if(mode==="refund")await purchasingService.refundPayment(paymentCode,{refunded_at:date,amount:Number(amount),reference:reference||undefined,note:note||undefined});if(mode==="receive"){const ls=(order.lines??[]).map(l=>({purchase_order_line_code:l.code,quantity:Number(lineQty[l.code]||0)})).filter(x=>x.quantity>0);if(!ls.length)throw new Error("Enter a received quantity for at least one item.");await purchasingService.receive(order.code,{received_at:date,lines:ls,note:note||undefined})}if(mode==="return"){const ls=receipts.flatMap(r=>r.lines.map(l=>({purchase_receipt_line_code:l.code,quantity:Number(lineQty[l.code]||0)}))).filter(x=>x.quantity>0);if(!ls.length)throw new Error("Enter a return quantity for at least one item.");await purchasingService.returnToSupplier(order.code,{returned_at:date,lines:ls,reason:returnReason||undefined,note:note||undefined})}setMode(null);setAmount("");setReference("");setReturnReason("");setNote("");setLineQty({});await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
  const returnedForReceiptLine = (code:string) => returns.reduce((sum, entry) => sum + entry.lines.filter(line => line.purchase_receipt_line_code === code).reduce((lineSum, line) => lineSum + Number(line.quantity), 0), 0);
  if(loading)return <main className="page-content"><LoadingState rows={6}/></main>;if(!order)return <main className="page-content"><Alert tone="danger" title="Unable to open purchase" message={error||"Purchase not found."}/><Link to={routePaths.purchasing}>Back to purchases</Link></main>;
  const canReceive=order.status==="CONFIRMED"&&order.receipt_status!=="RECEIVED";const outstanding=Math.max(0,Number(order.totals.amount)-Number(order.totals.net_paid_amount));
  return <main className="page-content"><SectionHeader title={`Purchase ${order.code}`} subtitle={`${order.supplier.name} · ${order.currency_code}`} action={<Link className="ui-button ui-button--secondary" to={routePaths.purchasing}>All purchases</Link>}/>
    {error&&<Alert tone="danger" title="Unable to complete action" message={error}/>}<div className="purchase-status-grid"><div><small>Order</small><Badge>{order.status}</Badge></div><div><small>Payment</small><Badge>{order.payment_status}</Badge></div><div><small>Receipt</small><Badge>{order.receipt_status}</Badge></div><div><small>Returns</small><Badge>{order.return_status}</Badge></div><div><small>Total</small><strong>{money(order.totals.amount,order.currency_code)}</strong></div><div><small>Still to pay</small><strong>{money(outstanding,order.currency_code)}</strong></div></div>
    <div className="purchasing-actions">{hasPermission("manage_purchase_order")&&order.status==="DRAFT"&&<Button isLoading={busy} onClick={()=>void action("order")}>Place order</Button>}{hasPermission("manage_purchase_order")&&order.status==="ORDERED"&&<Button isLoading={busy} onClick={()=>void action("confirm")}>Mark supplier confirmed</Button>}{hasPermission("manage_purchase_order")&&["DRAFT","ORDERED"].includes(order.status)&&<Button isLoading={busy} onClick={()=>void action("cancel")}>Cancel order</Button>}{hasPermission("manage_purchase_receipt")&&canReceive&&<Button onClick={()=>setMode("receive")}>Record goods received</Button>}{hasPermission("manage_purchase_payment")&&order.status!=="DRAFT"&&order.status!=="CANCELLED"&&outstanding>0&&<Button onClick={()=>{setAmount(String(outstanding));setMode("payment")}}>Record payment</Button>}{hasPermission("manage_purchase_return")&&receipts.length>0&&<Button onClick={()=>setMode("return")}>Return goods</Button>}</div>
    <section className="purchase-section"><h3>Items</h3><div className="ui-data-table__scroll"><table><thead><tr><th>Item</th><th>Tracking</th><th>Ordered</th><th>Received</th><th>Incoming</th><th>Unit price</th></tr></thead><tbody>{(order.lines??[]).map(l=><tr key={l.code}><td>{l.item_description}</td><td>{l.tracking_mode}</td><td>{l.ordered_quantity} {l.unit_label}</td><td>{l.received_quantity}</td><td>{l.incoming_quantity}</td><td>{money(l.unit_price,order.currency_code)}</td></tr>)}</tbody></table></div></section>
    <section className="purchase-section"><h3>Payments and refunds</h3>{payments.map(p=><div className="purchase-history" key={p.code}><strong>{p.code}</strong><span>{p.paid_at} · {money(p.amount,order.currency_code)} · refunded {money(p.refunded_amount,order.currency_code)}</span>{hasPermission("manage_purchase_payment")&&Number(p.amount)>Number(p.refunded_amount)&&<Button onClick={()=>{setPaymentCode(p.code);setAmount(String(Number(p.amount)-Number(p.refunded_amount)));setMode("refund")}}>Record refund</Button>}{p.refunds.map(refund=><small key={refund.code}>Refund {refund.code}: {refund.refunded_at} · {money(refund.amount,order.currency_code)}</small>)}</div>)}</section>
    <section className="purchase-section"><h3>Receipts and returns</h3>{receipts.map(r=><div className="purchase-history" key={r.code}><strong>{r.code}</strong><span>{r.received_at} · {r.lines.map(l=>`${l.quantity} (${l.purchase_order_line_code})`).join(", ")}</span></div>)}{returns.map(r=><div className="purchase-history" key={r.code}><strong>Return {r.code}</strong><span>{r.returned_at} · {r.lines.map(l=>`${l.quantity} (${l.purchase_receipt_line_code})`).join(", ")}</span></div>)}</section>
    {mode&&<div className="purchase-modal" role="dialog" aria-modal="true"><form className="purchase-modal__panel" onSubmit={submitAction}><SectionHeader title={mode==="payment"?"Record payment":mode==="refund"?"Record refund":mode==="receive"?"Record goods received":"Return goods"}/><FormField id="action-date" label="Date"><Input id="action-date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></FormField>
      {mode==="payment"||mode==="refund"?<FormField id="action-amount" label="Amount"><Input id="action-amount" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></FormField>:mode==="receive"?(order.lines??[]).map(l=><FormField key={l.code} id={`qty-${l.code}`} label={`${l.item_description} · remaining ${l.incoming_quantity}`}><Input id={`qty-${l.code}`} type="number" min="0" step={l.tracking_mode === "QUANTITY" ? "0.001" : "1"} max={l.incoming_quantity} value={lineQty[l.code]??""} onChange={e=>setLineQty(v=>({...v,[l.code]:e.target.value}))}/></FormField>):receipts.flatMap(r=>r.lines.map(l=>{const remaining=Math.max(0,Number(l.quantity)-returnedForReceiptLine(l.code));return <FormField key={l.code} id={`qty-${l.code}`} label={`Receipt ${r.code} · remaining received ${remaining}`}><Input id={`qty-${l.code}`} type="number" min="0" step="0.001" max={remaining} disabled={remaining===0} value={lineQty[l.code]??""} onChange={e=>setLineQty(v=>({...v,[l.code]:e.target.value}))}/></FormField>}))}
      {(mode==="payment"||mode==="refund")&&<FormField id="action-reference" label="Reference"><Input id="action-reference" value={reference} onChange={e=>setReference(e.target.value)}/></FormField>}{mode==="return"&&<FormField id="return-reason" label="Return reason"><Input id="return-reason" value={returnReason} onChange={e=>setReturnReason(e.target.value)}/></FormField>}
      <FormField id="action-note" label="Note"><Textarea id="action-note" value={note} onChange={e=>setNote(e.target.value)}/></FormField><div className="purchasing-actions"><Button onClick={()=>setMode(null)}>Cancel</Button><Button type="submit" variant="primary" isLoading={busy}>Save</Button></div></form></div>}
  </main>;
}
