import { useEffect, useState, type FormEvent } from 'react'
import { Navigate, useNavigate, useParams } from 'react-router'
import { routePaths } from '../../../app/routes/paths'
import { Button, Select } from '../../../components/atoms'
import { Alert, LoadingState } from '../../../components/feedback'
import { ActionBar, Card, FinancialAmountInput, FormField, FormGroup, KeyValueList, SectionHeader } from '../../../components/molecules'
import { DataTable, type DataTableColumn } from '../../../components/organisms'
import { createIdempotencyKey } from '../../../services/http/idempotency'
import { FinancialAccountSelect } from '../../financialAccounts/components/FinancialAccountSelect'
import { AccountCurrencyAmount } from '../../finance/AccountCurrencyAmount'
import type { FinancialUnitCode } from '../../finance/financialUnits'
import { ReportingExchangeRateField } from '../../finance/ReportingExchangeRateField'
import { formatDate } from '../../finance/financeFormat'
import { businessLoanService, type BusinessLoanCalculation, type BusinessLoanPayment } from '../services/businessLoanService'

const paymentColumns: Array<DataTableColumn<BusinessLoanPayment>> = [
  { header: 'Payment', key: 'code', render: (row) => <strong>{row.code}</strong> },
  { header: 'Amount', key: 'amount', render: (row) => row.payment_amount },
  { header: 'Principal', key: 'principal', render: (row) => row.principal_paid },
  { header: 'Interest', key: 'interest', render: (row) => row.interest_paid },
  { header: 'Allocation', key: 'allocation', render: (row) => row.allocation_order.replace('_', ' ') },
  { header: 'Paid at', key: 'date', render: (row) => formatDate(row.payment_at) },
]

export function BusinessLoanPaymentPage() {
  const { loanCode = '' } = useParams(); const navigate = useNavigate(); const [calculation, setCalculation] = useState<BusinessLoanCalculation | null>(null); const [history, setHistory] = useState<BusinessLoanPayment[]>([]); const [amount, setAmount] = useState(''); const [unit, setUnit] = useState<FinancialUnitCode>('UNIT'); const [accountId, setAccountId] = useState(''); const [order, setOrder] = useState<'interest_first' | 'principal_first'>('interest_first'); const [rate, setRate] = useState(''); const [inversed, setInversed] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)
  async function load() { if (!loanCode) return; setLoading(true); try { const [nextCalculation, nextHistory] = await Promise.all([businessLoanService.calculation(loanCode), businessLoanService.payments(loanCode)]); setCalculation(nextCalculation); setHistory(nextHistory) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load payment details.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [loanCode])
  if (!loanCode) return <Navigate replace to={routePaths.businessLoans} />
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!calculation) return; const paymentAmount = calculation.allow_partial_payments ? Number(amount) : Number(calculation.total_outstanding); setLoading(true); setError(null); try { await businessLoanService.pay(loanCode, { amount_paid: paymentAmount, amount_paid_unit: calculation.allow_partial_payments ? unit : 'UNIT', allocation_order: order, loan_update_key: calculation.loan_update_key, payment_account_id: accountId ? Number(accountId) : undefined, reporting_exchange_rate: rate ? Number(rate) : undefined, reporting_exchange_rate_inversed: inversed }, createIdempotencyKey()); setNotice('Business loan payment recorded.'); setAmount(''); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to record payment.') } finally { setLoading(false) } }
  return <section className="page business-loan-payment-page"><SectionHeader title="Business Loan Payment" subtitle={loanCode} action={<Button onClick={() => navigate(routePaths.businessLoanDetail(loanCode))} variant="secondary">Back</Button>} />{error && <Alert message={error} onDismiss={() => setError(null)} title="Payment failed" tone="danger" />}{notice && <Alert message={notice} onDismiss={() => setNotice(null)} title="Payment recorded" tone="success" />}{loading && !calculation ? <LoadingState rows={6} /> : calculation && <div className="business-loan-payment-layout"><Card title="Outstanding Balance" description="Current principal and accrued interest."><KeyValueList items={[{ key: 'Principal', value: <AccountCurrencyAmount accountId={calculation.account_id} amount={calculation.principal_balance} /> }, { key: 'Interest', value: <AccountCurrencyAmount accountId={calculation.account_id} amount={calculation.outstanding_interest} /> }, { key: 'Total', value: <AccountCurrencyAmount accountId={calculation.account_id} amount={calculation.total_outstanding} /> }]} /></Card><Card title="Record Payment" description="Allocate a payment against this business loan."><form className="ui-form" onSubmit={submit}><FormGroup columns={1}>{calculation.allow_partial_payments ? <FormField id="business-loan-payment-amount" label="Amount"><FinancialAmountInput id="business-loan-payment-amount" min="0.01" onChange={(next) => { setAmount(next.amount); setUnit(next.unit) }} step="0.01" value={{ amount, unit }} /></FormField> : <KeyValueList items={[{ key: 'Full settlement', value: <AccountCurrencyAmount accountId={calculation.account_id} amount={calculation.total_outstanding} /> }]} />}<FormField id="business-loan-payment-order" label="Allocation"><Select id="business-loan-payment-order" onChange={(event) => setOrder(event.target.value as typeof order)} value={order}><option value="interest_first">Interest first</option><option value="principal_first">Principal first</option></Select></FormField><FormField id="business-loan-payment-account" label="Payment Account" helperText="Only compatible accounts are available."><FinancialAccountSelect id="business-loan-payment-account" matchAccountId={calculation.account_id} onChange={setAccountId} value={accountId} /></FormField><ReportingExchangeRateField accountId={accountId || String(calculation.account_id)} inversed={inversed} manualRate={rate} onInversedChange={setInversed} onManualRateChange={setRate} /></FormGroup><ActionBar><Button disabled={calculation.allow_partial_payments && Number(amount) <= 0} isLoading={loading} type="submit">Record Payment</Button></ActionBar></form></Card><Card title="Payment History" description="Payments recorded against this loan."><DataTable columns={paymentColumns} emptyDescription="Payments will appear here after they are recorded." emptyTitle="No payments" getItemId={(row) => row.id} getItemTitle={(row) => row.code} items={history} /></Card></div>}</section>
}
