import { useCallback, useEffect, useState } from 'react'
import { useNavigate } from 'react-router'
import { routePaths } from '../../../app/routes/paths'
import { Badge, Button, Input } from '../../../components/atoms'
import { Alert, LoadingState } from '../../../components/feedback'
import { Card, FormField, SectionHeader } from '../../../components/molecules'
import { DataTable, type DataTableColumn } from '../../../components/organisms'
import { usePermissions } from '../../auth'
import { AccountCurrencyAmount } from '../../finance/AccountCurrencyAmount'
import { formatDate } from '../../finance/financeFormat'
import { businessLoanService, type BusinessLoan } from '../services/businessLoanService'

export function BusinessLoanListPage() {
  const navigate = useNavigate(); const { hasPermission } = usePermissions(); const [items, setItems] = useState<BusinessLoan[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); try { const result = await businessLoanService.list({ perPage: 100, search }); setItems(result.data) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load business loans.') } finally { setLoading(false) } }, [search])
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer) }, [load])
  async function remove(item: BusinessLoan) { if (!window.confirm(`Delete business loan "${item.code}"?`)) return; try { await businessLoanService.delete(item.code); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to delete business loan.') } }
  const actions = (row: BusinessLoan) => <div className="row-actions"><Button onClick={() => navigate(routePaths.businessLoanDetail(row.code))} variant="ghost">View</Button>{!row.is_paid && hasPermission('update_business_loan') && <Button onClick={() => navigate(routePaths.businessLoanPayment(row.code))} variant="secondary">Pay</Button>}{hasPermission('update_business_loan') && <Button onClick={() => navigate(routePaths.businessLoanEdit(row.code))} variant="secondary">Edit</Button>}{hasPermission('delete_business_loan') && <Button onClick={() => void remove(row)} variant="danger">Delete</Button>}</div>
  const columns: Array<DataTableColumn<BusinessLoan>> = [{ header: 'Loan', key: 'code', render: (row) => <strong>{row.code}</strong> }, { header: 'Lender', key: 'lender', render: (row) => row.lender_name }, { header: 'Outstanding', key: 'amount', render: (row) => <AccountCurrencyAmount accountId={row.receipt_account_id} amount={row.total_outstanding} /> }, { header: 'Interest', key: 'interest', render: (row) => row.apply_interest ? `${row.interest_rate}% ${row.interest_type_name ?? ''}` : '-' }, { header: 'Status', key: 'status', render: (row) => <Badge tone={row.is_paid ? 'success' : 'warning'}>{row.is_paid ? 'Settled' : 'Active'}</Badge> }, { header: 'Created', key: 'created', render: (row) => formatDate(row.created_at) }, { header: 'Actions', key: 'actions', render: actions }]
  return <section className="page business-loan-list-page"><SectionHeader title="Business Loans" subtitle="Track lender funding, interest expense, and repayments." action={hasPermission('create_business_loan') ? <Button onClick={() => navigate(routePaths.businessLoanCreate)}>Create Business Loan</Button> : null} />{error && <Alert message={error} onDismiss={() => setError(null)} title="Business loan action failed" tone="danger" />}<Card title="Business Loan Records"><FormField id="business-loan-search" label="Search"><Input id="business-loan-search" onChange={(event) => setSearch(event.target.value)} value={search} /></FormField>{loading ? <LoadingState rows={5} /> : <><div className="business-loan-list--desktop"><DataTable columns={columns} emptyDescription="Create a business loan to record lender funding." emptyTitle="No business loans" getItemId={(row) => row.id} getItemTitle={(row) => row.code} items={items} /></div><div className="business-loan-list--mobile">{items.map((item) => <article className="business-loan-mobile-card" key={item.id}><button onClick={() => navigate(routePaths.businessLoanDetail(item.code))} type="button"><strong>{item.code}</strong><span>{item.lender_name}</span><span>{item.total_outstanding}</span></button>{actions(item)}</article>)}</div></>}</Card></section>
}
