export const routePaths = {
  home: '/',
  login: '/login',
  sso: '/sso',
  dashboard: '/dashboard',
  profile: '/profile',
  profileChangePassword: '/profile/change-password',
  customers: '/customers',
  customerCreate: '/customers/create',
  customerDetail: (customerId: number | string) => `/customers/${customerId}`,
  customerEdit: (customerId: number | string) => `/customers/${customerId}/edit`,
  collateral: '/collateral',
  collateralDetail: (itemId: number | string) => `/collateral/${itemId}`,
  slips: '/slips',
  slipDetail: (slipNo: number | string) => `/slips/${slipNo}`,
  interest: '/interest',
  redemptions: '/redemptions',
  accounting: '/accounting',
  expenses: '/expenses',
  expenseCreate: '/expenses/create',
  debts: '/debts',
  debtCreate: '/debts/create',
  staff: '/staff',
  staffCreate: '/staff/create',
  staffDetail: (staffId: number | string) => `/staff/${staffId}`,
  staffEdit: (staffId: number | string) => `/staff/${staffId}/edit`,
  settings: '/settings',
  templateEditor: '/settings/template-editor',
} as const
