export const routePaths = {
  home: '/',
  login: '/login',
  sso: '/sso',
  dashboard: '/dashboard',
  profile: '/profile',
  profileChangePassword: '/profile/change-password',
  customers: '/customers',
  customerCreate: '/customers/create',
  customerDetail: (customerId: number | string) => `/customers/${customerId}`,
  customerEdit: (customerId: number | string) => `/customers/${customerId}/edit`,
  collateral: '/collateral',
  collateralDetail: (itemId: number | string) => `/collateral/${itemId}`,
  slips: '/slips',
  slipsForCustomer: (customerCode: string) => `/slips?customer=${encodeURIComponent(customerCode)}`,
  slipDetail: (slipNo: number | string) => `/slips/${slipNo}`,
  interest: '/interest',
  redemptions: '/redemptions',
  accounting: '/accounting',
  currencies: '/currencies',
  exchangePairs: '/exchange-pairs',
  dailyRates: '/daily-rates',
  reportingCurrencyRates: '/settings/reporting-currency-rates',
  financialAccounts: '/financial-accounts',
  financialAccountCreate: '/financial-accounts/create',
  financialAccountTransfer: '/financial-accounts/transfer',
  financialAccountDetail: (accountCode: string) => `/financial-accounts/${accountCode}`,
  financialAccountEdit: (accountCode: string) => `/financial-accounts/${accountCode}/edit`,
  capitals: '/capitals',
  capitalCreate: '/capitals/create',
  capitalEdit: (capitalCode: string) => `/capitals/${encodeURIComponent(capitalCode)}/edit`,
  expenses: '/expenses',
  expenseCreate: '/expenses/create',
  expenseEdit: (expenseCode: string) => `/expenses/${encodeURIComponent(expenseCode)}/edit`,
  debts: '/debts',
  debtCreate: '/debts/create',
  staff: '/staff',
  staffCreate: '/staff/create',
  staffDetail: (staffId: number | string) => `/staff/${staffId}`,
  staffEdit: (staffId: number | string) => `/staff/${staffId}/edit`,
  settings: '/settings',
  settingsPersonal: '/settings/personal',
  settingsTenant: '/settings/tenant',
  settingsFinance: '/settings/finance',
  settingsDefaultData: '/settings/default-data',
  settingsDocuments: '/settings/documents',
  templateEditor: '/settings/template-editor',
} as const
