import { useCallback, useEffect, useMemo, useState } from 'react'
import { Navigate, useNavigate, useParams } from 'react-router'
import { routePaths } from '../../../app/routes/paths'
import { Badge, Button, Input, Select } from '../../../components/atoms'
import { Alert, EmptyState, LoadingState } from '../../../components/feedback'
import { Card, FormField, KeyValueList, SectionHeader } from '../../../components/molecules'
import { usePermissions } from '../../auth'
import { financialAccountService } from '../financialAccountService'
import type { AssignedFinancialAccountUser, FinancialAccount, FinancialAccountDetail, FinancialAccountTransaction, FinancialAccountTransactionPage, FinancialAccountTransactionType } from '../types'

const transactionTypes: FinancialAccountTransactionType[] = ['OPENING_BALANCE', 'PAWN_LOAN_CREATION', 'PAWN_INTEREST_PAYMENT', 'PAWN_REDEMPTION', 'DEBT_CREATION', 'DEBT_PAYMENT', 'BUSINESS_LOAN_RECEIPT', 'BUSINESS_LOAN_PAYMENT', 'EXPENSE_PAYMENT', 'CAPITAL_CONTRIBUTION', 'CAPITAL_WITHDRAWAL', 'ACCOUNT_TRANSFER', 'TRANSFER_FEE', 'ADJUSTMENT', 'REVERSAL']
const emptyPage: FinancialAccountTransactionPage = { items: [], current_page: 1, last_page: 1, per_page: 15, total: 0 }
type Filters = { search: string; direction: '' | 'debit' | 'credit'; transactionType: '' | FinancialAccountTransactionType; startDate: string; endDate: string }
const emptyFilters: Filters = { search: '', direction: '', transactionType: '', startDate: '', endDate: '' }

export function FinancialAccountDetailPage() {
  const navigate = useNavigate(); const { accountCode: rawCode } = useParams(); const accountCode = rawCode?.trim() ?? ''; const { hasPermission } = usePermissions()
  const [account, setAccount] = useState<FinancialAccountDetail | null>(null); const [page, setPage] = useState(emptyPage); const [pageNumber, setPageNumber] = useState(1)
  const [filters, setFilters] = useState(emptyFilters); const [debouncedSearch, setDebouncedSearch] = useState(''); const [loadingAccount, setLoadingAccount] = useState(true); const [loadingHistory, setLoadingHistory] = useState(true); const [error, setError] = useState<string | null>(null)

  useEffect(() => { const timer = window.setTimeout(() => { setDebouncedSearch(filters.search.trim()); setPageNumber(1) }, 300); return () => window.clearTimeout(timer) }, [filters.search])
  useEffect(() => { if (!accountCode) return; const timer = window.setTimeout(() => { setLoadingAccount(true); financialAccountService.get(accountCode).then(setAccount).catch((reason) => setError(message(reason, 'Unable to load financial account.'))).finally(() => setLoadingAccount(false)) }, 0); return () => window.clearTimeout(timer) }, [accountCode])
  const historyFilters = useMemo(() => ({ page: pageNumber, search: debouncedSearch || undefined, direction: filters.direction || undefined, transactionType: filters.transactionType || undefined, startAt: filters.startDate ? localBoundary(filters.startDate, false) : undefined, endAt: filters.endDate ? localBoundary(filters.endDate, true) : undefined }), [debouncedSearch, filters.direction, filters.endDate, filters.startDate, filters.transactionType, pageNumber])
  const loadHistory = useCallback(async () => { if (!accountCode) return; setLoadingHistory(true); setError(null); try { setPage(await financialAccountService.transactions(accountCode, historyFilters)) } catch (reason) { setError(message(reason, 'Unable to load transaction history.')) } finally { setLoadingHistory(false) } }, [accountCode, historyFilters])
  useEffect(() => { const timer = window.setTimeout(() => void loadHistory(), 0); return () => window.clearTimeout(timer) }, [loadHistory])
  if (!accountCode) return <Navigate replace to={routePaths.financialAccounts} />
  const updateFilter = <K extends keyof Filters>(key: K, value: Filters[K]) => { setFilters((current) => ({ ...current, [key]: value })); if (key !== 'search') setPageNumber(1) }

  return <section className="page financial-account-detail-page">
    <SectionHeader title="Account Detail" subtitle="Review account information and immutable transaction history." action={<div className="financial-account-detail-actions"><Button onClick={() => navigate(routePaths.financialAccounts)} variant="ghost">Back</Button>{account && hasPermission('update_financial_account') && <Button onClick={() => navigate(routePaths.financialAccountEdit(account.account_code))} variant="primary">Edit Account</Button>}</div>} />
    {error && <Alert message={error} onDismiss={() => setError(null)} title="Account history failed" tone="danger" />}
    {loadingAccount ? <LoadingState rows={3} /> : account ? <AccountSummary account={account} /> : !error && <EmptyState title="Account not found" description="This financial account is unavailable." />}
    {account && hasPermission('manage_financial_account_assignments') && <AssignedUsers users={account.assigned_users} />}
    {account && <Card title="Transaction History" description={`${page.total} ledger ${page.total === 1 ? 'entry' : 'entries'}`}>
      <HistoryFilters filters={filters} onChange={updateFilter} onClear={() => { setFilters(emptyFilters); setDebouncedSearch(''); setPageNumber(1) }} />
      {loadingHistory ? <LoadingState rows={5} /> : page.items.length === 0 ? <EmptyState title={hasFilters(filters) ? 'No matching transactions' : 'No transactions'} description={hasFilters(filters) ? 'Clear or change the filters to see more results.' : 'Transactions posted to this account will appear here.'} /> : <><TransactionDesktopTable account={account} items={page.items} /><TransactionMobileCards account={account} items={page.items} /></>}
      {!loadingHistory && page.total > 0 && <div className="financial-account-history-pagination"><span>Page {page.current_page} of {page.last_page} · {page.total} records</span><div><Button disabled={page.current_page <= 1} onClick={() => setPageNumber((value) => Math.max(1, value - 1))}>Previous</Button><Button disabled={page.current_page >= page.last_page} onClick={() => setPageNumber((value) => Math.min(page.last_page, value + 1))}>Next</Button></div></div>}
    </Card>}
  </section>
}

function AssignedUsers({ users }: { users: AssignedFinancialAccountUser[] }) {
  return <Card title="Assigned Staff" description={`${users.length} staff member${users.length === 1 ? '' : 's'} can use this account.`}>
    {users.length === 0 ? <EmptyState title="No assigned staff" description="Assign this account from a staff edit page." /> : <><div className="financial-account-users--desktop"><table><thead><tr><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.name}</strong><small>{user.code}</small></td><td>{user.role_name ?? '—'}</td><td><Badge tone={user.status === 'active' ? 'success' : 'warning'}>{user.status}</Badge></td></tr>)}</tbody></table></div><div className="financial-account-users--mobile">{users.map((user) => <article className="financial-account-user-card" key={user.id}><div><strong>{user.name}</strong><span>{user.code} · {user.role_name ?? 'No role'}</span></div><Badge tone={user.status === 'active' ? 'success' : 'warning'}>{user.status}</Badge></article>)}</div></>}
  </Card>
}

function AccountSummary({ account }: { account: FinancialAccount }) { return <Card title={account.account_name} description={account.account_code} action={<div className="row-actions">{account.is_default && <Badge tone="info">Default</Badge>}<Badge tone={account.is_active ? 'success' : 'warning'}>{account.is_active ? 'Active' : 'Inactive'}</Badge></div>}><div className="financial-account-detail-summary"><div className="financial-account-detail-balance"><span>Current balance</span><strong>{money(account.balance, account)}</strong></div><KeyValueList items={[{ key: 'Account number', value: account.account_number ?? '—' }, { key: 'Account type', value: account.account_type.name }, { key: 'Currency', value: `${account.currency.code} · ${account.currency.name}` }, { key: 'Negative balance', value: account.allow_negative_balance ? 'Allowed' : 'Not allowed' }]} /></div></Card> }

function HistoryFilters({ filters, onChange, onClear }: { filters: Filters; onChange: <K extends keyof Filters>(key: K, value: Filters[K]) => void; onClear: () => void }) { return <div className="financial-account-history-filters"><FormField id="account-history-search" label="Search"><Input id="account-history-search" placeholder="Type, reference, or note" value={filters.search} onChange={(event) => onChange('search', event.target.value)} /></FormField><details className="financial-account-history-filters--mobile"><summary>More filters</summary><FilterControls filters={filters} onChange={onChange} /></details><div className="financial-account-history-filters--desktop"><FilterControls filters={filters} onChange={onChange} /></div><Button onClick={onClear} variant="ghost">Clear filters</Button></div> }
function FilterControls({ filters, onChange }: { filters: Filters; onChange: <K extends keyof Filters>(key: K, value: Filters[K]) => void }) { return <><FormField id="account-history-direction" label="Direction"><Select id="account-history-direction" value={filters.direction} onChange={(event) => onChange('direction', event.target.value as Filters['direction'])}><option value="">All directions</option><option value="debit">Money in</option><option value="credit">Money out</option></Select></FormField><FormField id="account-history-type" label="Type"><Select id="account-history-type" value={filters.transactionType} onChange={(event) => onChange('transactionType', event.target.value as Filters['transactionType'])}><option value="">All types</option>{transactionTypes.map((type) => <option key={type} value={type}>{typeLabel(type)}</option>)}</Select></FormField><FormField id="account-history-start" label="From"><Input id="account-history-start" type="date" value={filters.startDate} onChange={(event) => onChange('startDate', event.target.value)} /></FormField><FormField id="account-history-end" label="To"><Input id="account-history-end" min={filters.startDate || undefined} type="date" value={filters.endDate} onChange={(event) => onChange('endDate', event.target.value)} /></FormField></> }

function TransactionDesktopTable({ account, items }: { account: FinancialAccount; items: FinancialAccountTransaction[] }) { return <div className="financial-account-history--desktop"><table><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Note</th><th>Created by</th><th>Direction</th><th>Amount</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{dateTime(item.created_at)}</td><td><strong>{typeLabel(item.transaction_type)}</strong><small>#{item.id}</small></td><td>{item.reference_number ?? '—'}<small>{item.reference_type ? referenceLabel(item.reference_type) : ''}</small></td><td>{item.note ?? '—'}</td><td>{item.creator?.name ?? 'System'}</td><td><Badge tone={item.direction === 'debit' ? 'success' : 'warning'}>{item.direction === 'debit' ? 'Money in' : 'Money out'}</Badge></td><td className={item.direction === 'debit' ? 'amount-in' : 'amount-out'}>{item.direction === 'debit' ? '+' : '−'}{money(item.amount, account)}</td></tr>)}</tbody></table></div> }
function TransactionMobileCards({ account, items }: { account: FinancialAccount; items: FinancialAccountTransaction[] }) { return <div className="financial-account-history--mobile">{items.map((item) => <article className="slip-history-mobile-card financial-account-transaction-card" key={item.id}><header className="slip-history-mobile-card__header"><div><small>{item.creator?.name ?? 'System'} · Transaction #{item.id}</small><strong>{typeLabel(item.transaction_type)}</strong></div><Badge tone={item.direction === 'debit' ? 'success' : 'warning'}>{item.direction === 'debit' ? 'Money in' : 'Money out'}</Badge></header><div className="slip-history-mobile-card__summary"><div><span>Amount</span><strong className={item.direction === 'debit' ? 'amount-in' : 'amount-out'}>{item.direction === 'debit' ? '+' : '−'}{money(item.amount, account)}</strong></div><span>{dateTime(item.created_at)}</span></div><footer className="slip-history-mobile-card__footer financial-account-transaction-card__footer"><div><small>Reference</small><strong>{item.reference_number ?? '—'}</strong>{item.reference_type && <span>{referenceLabel(item.reference_type)}</span>}</div><div><small>Note</small><span>{item.note ?? '—'}</span></div></footer></article>)}</div> }

function money(value: string, account: FinancialAccount) { return `${account.currency.symbol ?? account.currency.code} ${Number(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` }
function typeLabel(value: string) { return value.toLowerCase().split('_').map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(' ') }
function referenceLabel(value: string) { return value.split('\\').pop() ?? value }
function dateTime(value: string | null) { return value ? new Date(value).toLocaleString() : '—' }
function localBoundary(date: string, end: boolean) { const value = new Date(`${date}T${end ? '23:59:59.999' : '00:00:00.000'}`); return value.toISOString() }
function hasFilters(filters: Filters) { return Object.values(filters).some(Boolean) }
function message(reason: unknown, fallback: string) { return reason instanceof Error ? reason.message : fallback }
