import { FormField, SearchableSelect } from '../../../components/molecules'
import { Input, Select } from '../../../components/atoms'
import type { Currency, ExchangeRatePair } from '../types'

export function CurrencyCodeField({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <FormField id="currency-code" label="Code"><Input id="currency-code" maxLength={12} onChange={(event) => onChange(event.target.value.toUpperCase())} value={value} /></FormField> }
export function CurrencyNameField({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <FormField id="currency-name" label="Name"><Input id="currency-name" onChange={(event) => onChange(event.target.value)} value={value} /></FormField> }
export function CurrencySymbolField({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <FormField id="currency-symbol" label="Symbol"><Input id="currency-symbol" maxLength={12} onChange={(event) => onChange(event.target.value)} value={value} /></FormField> }

export function CurrencyPrecisionField({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <FormField id="currency-precision" label="Decimal precision"><Input id="currency-precision" max="8" min="0" onChange={(event) => onChange(event.target.value)} type="number" value={value} /></FormField> }
export function CurrencyAdjustmentField({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <FormField id="currency-adjustment" label="Adjustment step"><Input id="currency-adjustment" inputMode="decimal" onChange={(event) => onChange(event.target.value)} placeholder="Optional" value={value} /></FormField> }
export function CurrencyRoundingField({ value, onChange }: { value: Currency['rounding_mode']; onChange: (value: Currency['rounding_mode']) => void }) { return <FormField id="currency-rounding" label="Rounding"><Select id="currency-rounding" onChange={(event) => onChange(event.target.value as Currency['rounding_mode'])} value={value}>{['HALF_UP','HALF_DOWN','HALF_EVEN','UP','DOWN'].map((mode) => <option key={mode} value={mode}>{mode}</option>)}</Select></FormField> }
export function ExchangeCurrencyField({ id, label, currencies, value, onChange }: { id: string; label: string; currencies: Currency[]; value: string; onChange: (value: string) => void }) { return <FormField id={id} label={label}><Select id={id} onChange={(event) => onChange(event.target.value)} value={value}><option value="">Select currency</option>{currencies.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.code}>{item.code} — {item.name}</option>)}</Select></FormField> }
export function ExchangeRateValueField({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <FormField id="exchange-rate-value" label="Rate"><Input id="exchange-rate-value" inputMode="decimal" onChange={(event) => onChange(event.target.value)} value={value} /></FormField> }
export function ExchangePairSearchField({ id, pairs, value, onChange }: { id: string; pairs: ExchangeRatePair[]; value: string; onChange: (value: string) => void }) { return <FormField id={id} label="Exchange pair"><SearchableSelect id={id} options={pairs.filter((pair) => pair.is_active)} value={value} onChange={onChange} getOptionValue={(pair) => pair.code} getOptionLabel={(pair) => pair.display_code} getOptionDescription={(pair) => `${pair.base_currency.name} / ${pair.quote_currency.name}`} placeholder="Search exchange pairs" /></FormField> }
