import { apiClient } from '../../../services/http/apiClient'

type TenantAuth = {
  token?: string
  tenantCode?: string
}

export type TenantCustomer = {
  id: number
  code: string
  update_key?: number
  updateKey?: number
  tenantId?: number
  tenant_id?: number
  name: string
  nrc?: string | null
  nrc_citizen?: string | null
  nrc_number?: string | null
  nrc_state?: string | null
  nrc_township?: string | null
  email?: string | null
  phone?: string | null
  address?: string | null
  trustScore?: number
  trust_score?: number
  displayTrustScore?: number
  display_trust_score?: number
  activeSlipCount?: number
  active_slip_count?: number
  primaryLocation?: string
  primary_location?: string
  lastActivity?: TenantCustomerLastActivity
  last_activity?: TenantCustomerLastActivity
  note?: string | null
  created_by?: number | null
  createdBy?: number | null
  is_auto_generated?: boolean
  isAutoGenerated?: boolean
  is_deleted: boolean
  isDeleted?: boolean
  deleted_at?: string | null
  deletedAt?: string | null
  created_at?: string | null
  createdAt?: string | null
  loanMetrics?: TenantCustomerLoanMetrics
  loan_metrics?: TenantCustomerLoanMetrics
  activeSlips?: TenantCustomerActiveSlip[]
  active_slips?: TenantCustomerActiveSlip[]
  unpaidDebts?: TenantCustomerUnpaidDebt[]
  unpaid_debts?: TenantCustomerUnpaidDebt[]
}

export type TenantCustomerLastActivity = {
  date?: string | null
  status: string
  label: string
  tone: 'success' | 'danger' | 'neutral' | 'warning' | 'info' | string
}

export type TenantCustomerLoanMetrics = {
  total_slips?: number
  totalSlips?: number
  active_slips?: number
  activeSlips?: number
  completed_slips?: number
  completedSlips?: number
  total_loan_amount?: number
  totalLoanAmount?: number
  active_loan_amount?: number
  activeLoanAmount?: number
  total_interest_paid?: number
  totalInterestPaid?: number
  average_loan_term_days?: number
  averageLoanTermDays?: number
  redemption_rate?: number
  redemptionRate?: number
  latest_activity_date?: string | null
  latestActivityDate?: string | null
  first_slip_date?: string | null
  firstSlipDate?: string | null
}

export type TenantCustomerActiveSlip = {
  id: number
  slip_no?: string
  slipNo?: string
  pawned_item?: string
  pawnedItem?: string
  loan_amount?: number
  loanAmount?: number
  interest_rate?: number
  interestRate?: number
  interest_type_name?: string | null
  interestTypeName?: string | null
  expire_at?: string | null
  status?: string
}

export type TenantCustomerUnpaidDebt = {
  id: number
  code?: string
  amount?: number
  tag?: string | null
  created_at?: string | null
  createdAt?: string | null
}

export type TenantCustomerListSummary = {
  totalClients?: number
  total_clients?: number
  averageTrustScore?: number
  average_trust_score?: number
  activePawnLoans?: number
  active_pawn_loans?: number
  riskFlagged?: number
  risk_flagged?: number
}

export type TenantCustomerListPage = {
  items: TenantCustomer[]
  summary?: TenantCustomerListSummary
  currentPage?: number
  current_page?: number
  lastPage?: number
  last_page?: number
  perPage?: number
  per_page?: number
  total: number
}

export type TenantCustomerUpsertResult = {
  created?: boolean
  customer: TenantCustomer
}

function authOptions(auth: TenantAuth = {}) {
  return {
    tenantCode: auth.tenantCode,
    token: auth.token,
  }
}

export const customerService = {
  listCustomers(params: { page?: number; perPage?: number; search?: string; showUnknownCustomer?: boolean } = {}, auth?: TenantAuth) {
    const searchParams = new URLSearchParams()

    if (params.page !== undefined) {
      searchParams.set('page', String(params.page))
    }

    if (params.perPage !== undefined) {
      searchParams.set('per_page', String(params.perPage))
    }

    if (params.search?.trim()) {
      searchParams.set('search', params.search.trim())
    }

    if (params.showUnknownCustomer) {
      searchParams.set('show_unknown_customer', '1')
    }

    const query = searchParams.toString()

    return apiClient.get<TenantCustomerListPage>(
      `/tenant/customers${query ? `?${query}` : ''}`,
      authOptions(auth),
    )
  },

  createCustomer(payload: unknown, auth?: TenantAuth) {
    return apiClient.post<TenantCustomerUpsertResult>('/tenant/customers', payload, authOptions(auth))
  },

  getCustomer(tenantCustomerCode: string, auth?: TenantAuth) {
    return apiClient.get<TenantCustomer>(`/tenant/customers/${encodeURIComponent(tenantCustomerCode)}`, authOptions(auth))
  },

  updateCustomer(tenantCustomerCode: string, payload: unknown, auth?: TenantAuth) {
    return apiClient.put<TenantCustomer>(`/tenant/customers/${encodeURIComponent(tenantCustomerCode)}`, payload, authOptions(auth))
  },

  deleteCustomer(tenantCustomerCode: string, auth?: TenantAuth) {
    return apiClient.deleteMessage(`/tenant/customers/${encodeURIComponent(tenantCustomerCode)}`, authOptions(auth))
  },
}
